// ============================================================
//  Mabuhay! — Filipino Vocabulary Database
//  Each entry: { fil, eng, category, romanization?, example? }
// ============================================================

const VOCAB = [
  // ── GREETINGS & PLEASANTRIES ────────────────────────────
  { fil: "Kumusta?",           eng: "How are you? / Hello",       category: "greetings", example: "Kumusta ka? — How are you?" },
  { fil: "Mabuhay!",           eng: "Welcome! / Long live! / Cheers!", category: "greetings", example: "Mabuhay sa Pilipinas! — Welcome to the Philippines!" },
  { fil: "Magandang umaga",    eng: "Good morning",               category: "greetings", example: "Magandang umaga po! — Good morning (polite)." },
  { fil: "Magandang hapon",    eng: "Good afternoon",             category: "greetings" },
  { fil: "Magandang gabi",     eng: "Good evening",               category: "greetings" },
  { fil: "Paalam",             eng: "Goodbye / Farewell",         category: "greetings", example: "Paalam na! — Goodbye now!" },
  { fil: "Salamat",            eng: "Thank you",                  category: "greetings", example: "Maraming salamat — Thank you very much." },
  { fil: "Walang anuman",      eng: "You're welcome",             category: "greetings" },
  { fil: "Oo",                 eng: "Yes",                        category: "greetings" },
  { fil: "Hindi",              eng: "No",                         category: "greetings" },
  { fil: "Paumanhin",          eng: "Excuse me / I'm sorry",      category: "greetings", example: "Paumanhin, nasaan ang banyo? — Excuse me, where is the restroom?" },
  { fil: "Po / Opo",           eng: "Polite particle / Yes (polite)", category: "greetings", example: "Used to show respect to elders." },
  { fil: "Sige",               eng: "Okay / Go ahead / Sure",     category: "greetings", example: "Sige, tara na! — Okay, let's go!" },
  { fil: "Naman",              eng: "Also / Indeed (emphasis)",   category: "greetings", example: "Oo naman — Of course." },
  { fil: "Tara / Halika",      eng: "Come on / Let's go",         category: "greetings", example: "Tara, kumain tayo! — Come on, let's eat!" },

  // ── COMMON PHRASES ──────────────────────────────────────
  { fil: "Ano ang pangalan mo?",     eng: "What is your name?",          category: "phrases" },
  { fil: "Ang pangalan ko ay…",      eng: "My name is…",                 category: "phrases" },
  { fil: "Saan ka galing?",          eng: "Where are you from?",         category: "phrases" },
  { fil: "Hindi ko maintindihan",    eng: "I don't understand",          category: "phrases" },
  { fil: "Pakiulit",                 eng: "Please repeat that",          category: "phrases" },
  { fil: "Nagsasalita ka ba ng Ingles?", eng: "Do you speak English?",   category: "phrases" },
  { fil: "Magkano?",                 eng: "How much?",                   category: "phrases", example: "Magkano ang isda? — How much is the fish?" },
  { fil: "Nasaan ang…?",            eng: "Where is…?",                  category: "phrases" },
  { fil: "Gusto ko…",               eng: "I want / I like…",            category: "phrases", example: "Gusto ko ng kape — I want coffee." },
  { fil: "Kailangan ko…",           eng: "I need…",                     category: "phrases" },
  { fil: "Gutom na ako",             eng: "I'm hungry",                  category: "phrases" },
  { fil: "Uhaw na ako",              eng: "I'm thirsty",                 category: "phrases" },
  { fil: "Pagod na ako",             eng: "I'm tired",                   category: "phrases" },
  { fil: "Masaya ako",               eng: "I am happy",                  category: "phrases" },
  { fil: "Mahal kita",               eng: "I love you",                  category: "phrases" },
  { fil: "Miss na kita",             eng: "I miss you",                  category: "phrases" },
  { fil: "Tulong!",                  eng: "Help!",                       category: "phrases" },
  { fil: "Huwag!",                   eng: "Don't! / Stop!",              category: "phrases" },
  { fil: "Sandali lang",             eng: "Just a moment / Wait",        category: "phrases" },
  { fil: "Bakit?",                   eng: "Why?",                        category: "phrases" },
  { fil: "Kailan?",                  eng: "When?",                       category: "phrases" },
  { fil: "Sino?",                    eng: "Who?",                        category: "phrases" },
  { fil: "Ano?",                     eng: "What?",                       category: "phrases" },
  { fil: "Gaano?",                   eng: "How much / How many?",        category: "phrases" },
  { fil: "Alam mo ba?",              eng: "Do you know?",                category: "phrases" },

  // ── NUMBERS ─────────────────────────────────────────────
  { fil: "Isa",       eng: "One (1)",    category: "numbers" },
  { fil: "Dalawa",    eng: "Two (2)",    category: "numbers" },
  { fil: "Tatlo",     eng: "Three (3)", category: "numbers" },
  { fil: "Apat",      eng: "Four (4)",  category: "numbers" },
  { fil: "Lima",      eng: "Five (5)",  category: "numbers" },
  { fil: "Anim",      eng: "Six (6)",   category: "numbers" },
  { fil: "Pito",      eng: "Seven (7)", category: "numbers" },
  { fil: "Walo",      eng: "Eight (8)", category: "numbers" },
  { fil: "Siyam",     eng: "Nine (9)",  category: "numbers" },
  { fil: "Sampu",     eng: "Ten (10)",  category: "numbers" },
  { fil: "Labing-isa",eng: "Eleven (11)", category: "numbers" },
  { fil: "Labindalawa",eng: "Twelve (12)", category: "numbers" },
  { fil: "Dalawampu", eng: "Twenty (20)", category: "numbers" },
  { fil: "Tatlumpu",  eng: "Thirty (30)", category: "numbers" },
  { fil: "Isang daan",eng: "One hundred (100)", category: "numbers" },
  { fil: "Isang libo", eng: "One thousand (1,000)", category: "numbers" },

  // ── FAMILY ──────────────────────────────────────────────
  { fil: "Pamilya",    eng: "Family",            category: "family" },
  { fil: "Nanay / Inay", eng: "Mother / Mom",    category: "family" },
  { fil: "Tatay / Itay", eng: "Father / Dad",    category: "family" },
  { fil: "Kapatid",    eng: "Sibling",            category: "family" },
  { fil: "Kuya",       eng: "Older brother",      category: "family", example: "Also used as a respectful address for older men." },
  { fil: "Ate",        eng: "Older sister",        category: "family", example: "Also used as a respectful address for older women." },
  { fil: "Anak",       eng: "Child / Son / Daughter", category: "family" },
  { fil: "Lolo",       eng: "Grandfather",        category: "family" },
  { fil: "Lola",       eng: "Grandmother",        category: "family" },
  { fil: "Tito",       eng: "Uncle",              category: "family" },
  { fil: "Tita",       eng: "Aunt",               category: "family" },
  { fil: "Pinsan",     eng: "Cousin",             category: "family" },
  { fil: "Asawa",      eng: "Spouse",             category: "family" },
  { fil: "Lalaki",     eng: "Man / Male",         category: "family" },
  { fil: "Babae",      eng: "Woman / Female",     category: "family" },
  { fil: "Bata",       eng: "Child / Young",      category: "family" },

  // ── FOOD & DRINK ────────────────────────────────────────
  { fil: "Kanin",    eng: "Cooked rice",           category: "food" },
  { fil: "Ulam",     eng: "Viand / Side dish",     category: "food", example: "The dish eaten with rice." },
  { fil: "Asin",     eng: "Salt",                  category: "food" },
  { fil: "Asukal",   eng: "Sugar",                 category: "food" },
  { fil: "Tubig",    eng: "Water",                 category: "food" },
  { fil: "Gatas",    eng: "Milk",                  category: "food" },
  { fil: "Kape",     eng: "Coffee",                category: "food" },
  { fil: "Tinapay",  eng: "Bread",                 category: "food" },
  { fil: "Karne",    eng: "Meat",                  category: "food" },
  { fil: "Isda",     eng: "Fish",                  category: "food" },
  { fil: "Manok",    eng: "Chicken",               category: "food" },
  { fil: "Baboy",    eng: "Pig / Pork",            category: "food" },
  { fil: "Gulay",    eng: "Vegetables",            category: "food" },
  { fil: "Prutas",   eng: "Fruit",                 category: "food" },
  { fil: "Itlog",    eng: "Egg",                   category: "food" },
  { fil: "Adobo",    eng: "Adobo (vinegar & soy dish)", category: "food", example: "The most iconic Filipino dish." },
  { fil: "Sinigang", eng: "Sinigang (sour tamarind soup)", category: "food" },
  { fil: "Sorbetes", eng: "Ice cream",             category: "food" },
  { fil: "Merienda", eng: "Afternoon snack",       category: "food", example: "A beloved Filipino tradition of a light mid-afternoon meal." },

  // ── TRAVEL ──────────────────────────────────────────────
  { fil: "Eroplano",   eng: "Airplane",            category: "travel" },
  { fil: "Barko",      eng: "Ship / Boat",         category: "travel" },
  { fil: "Jeepney",    eng: "Jeepney (local bus)", category: "travel", example: "The iconic, colorfully decorated Filipino public transport." },
  { fil: "Trike",      eng: "Tricycle (motorbike sidecar)", category: "travel" },
  { fil: "Paliparan",  eng: "Airport",             category: "travel" },
  { fil: "Daan",       eng: "Road / Street",       category: "travel" },
  { fil: "Tulay",      eng: "Bridge",              category: "travel" },
  { fil: "Ospital",    eng: "Hospital",            category: "travel" },
  { fil: "Simbahan",   eng: "Church",              category: "travel" },
  { fil: "Palengke",   eng: "Market",              category: "travel" },
  { fil: "Bangko",     eng: "Bank",                category: "travel" },
  { fil: "Paaralan",   eng: "School",              category: "travel" },
  { fil: "Bahay",      eng: "House / Home",        category: "travel" },
  { fil: "Banyo",      eng: "Bathroom / Restroom", category: "travel" },
  { fil: "Kanan",      eng: "Right (direction)",   category: "travel" },
  { fil: "Kaliwa",     eng: "Left (direction)",    category: "travel" },
  { fil: "Diretso",    eng: "Straight ahead",      category: "travel" },
  { fil: "Malapit",    eng: "Near / Close",        category: "travel" },
  { fil: "Malayo",     eng: "Far",                 category: "travel" },

  // ── COLORS ──────────────────────────────────────────────
  { fil: "Pula",         eng: "Red",     category: "colors" },
  { fil: "Berde",        eng: "Green",   category: "colors" },
  { fil: "Asul",         eng: "Blue",    category: "colors" },
  { fil: "Dilaw",        eng: "Yellow",  category: "colors" },
  { fil: "Puti",         eng: "White",   category: "colors" },
  { fil: "Itim",         eng: "Black",   category: "colors" },
  { fil: "Kulay-abo",    eng: "Gray",    category: "colors" },
  { fil: "Kahel",        eng: "Orange",  category: "colors" },
  { fil: "Rosas",        eng: "Pink",    category: "colors" },
  { fil: "Kayumanggi",   eng: "Brown",   category: "colors" },
  { fil: "Lila / Ube",   eng: "Purple",  category: "colors" },

  // ── TIME & DAYS ──────────────────────────────────────────
  { fil: "Ngayon",       eng: "Now / Today",        category: "time" },
  { fil: "Bukas",        eng: "Tomorrow",            category: "time" },
  { fil: "Kahapon",      eng: "Yesterday",           category: "time" },
  { fil: "Umaga",        eng: "Morning",             category: "time" },
  { fil: "Tanghali",     eng: "Noon / Midday",       category: "time" },
  { fil: "Hapon",        eng: "Afternoon",           category: "time" },
  { fil: "Gabi",         eng: "Evening / Night",     category: "time" },
  { fil: "Lunes",        eng: "Monday",              category: "time" },
  { fil: "Martes",       eng: "Tuesday",             category: "time" },
  { fil: "Miyerkules",   eng: "Wednesday",           category: "time" },
  { fil: "Huwebes",      eng: "Thursday",            category: "time" },
  { fil: "Biyernes",     eng: "Friday",              category: "time" },
  { fil: "Sabado",       eng: "Saturday",            category: "time" },
  { fil: "Linggo",       eng: "Sunday / Week",       category: "time", example: "Linggo also means 'week'." },
  { fil: "Taon",         eng: "Year",                category: "time" },
  { fil: "Buwan",        eng: "Month / Moon",        category: "time" },
  { fil: "Oras",         eng: "Hour / Time",         category: "time" },

  // ── COMMON VERBS ─────────────────────────────────────────
  { fil: "Kumain",    eng: "To eat",         category: "verbs", example: "Kumain tayo! — Let's eat!" },
  { fil: "Uminom",    eng: "To drink",       category: "verbs" },
  { fil: "Matulog",   eng: "To sleep",       category: "verbs" },
  { fil: "Gumising",  eng: "To wake up",     category: "verbs" },
  { fil: "Maglakad",  eng: "To walk",        category: "verbs" },
  { fil: "Tumakbo",   eng: "To run",         category: "verbs" },
  { fil: "Magtrabaho",eng: "To work",        category: "verbs" },
  { fil: "Mag-aral",  eng: "To study",       category: "verbs" },
  { fil: "Maglaro",   eng: "To play",        category: "verbs" },
  { fil: "Manood",    eng: "To watch",       category: "verbs" },
  { fil: "Makinig",   eng: "To listen",      category: "verbs" },
  { fil: "Magsalita", eng: "To speak / talk",category: "verbs" },
  { fil: "Bumasa",    eng: "To read",        category: "verbs" },
  { fil: "Sumulat",   eng: "To write",       category: "verbs" },
  { fil: "Bumili",    eng: "To buy",         category: "verbs" },
  { fil: "Magbayad",  eng: "To pay",         category: "verbs" },
  { fil: "Pumunta",   eng: "To go (to a place)", category: "verbs" },
  { fil: "Bumalik",   eng: "To return / come back", category: "verbs" },
  { fil: "Umalis",    eng: "To leave",       category: "verbs" },
  { fil: "Lumapit",   eng: "To come near / approach", category: "verbs" },
  { fil: "Magbigay",  eng: "To give",        category: "verbs" },
  { fil: "Kumuha",    eng: "To take / get",  category: "verbs" },
  { fil: "Magtanong", eng: "To ask",         category: "verbs" },
  { fil: "Sumagot",   eng: "To answer",      category: "verbs" },
  { fil: "Tumulong",  eng: "To help",        category: "verbs" },

  // More verbs — intermediate/advanced forms
  { fil: "Magpahinga",  eng: "To rest",                category: "verbs" },
  { fil: "Magtago",     eng: "To hide (something)",    category: "verbs", example: "Nagtago siya ng pera — He hid money." },
  { fil: "Lumipat",     eng: "To move / transfer",     category: "verbs", example: "Lumipat kami ng bahay — We moved houses." },
  { fil: "Magpalit",    eng: "To change / exchange",   category: "verbs" },
  { fil: "Umasa",       eng: "To hope / rely on",      category: "verbs", example: "Huwag kang umasa — Don't get your hopes up." },
  { fil: "Magising",    eng: "To wake (someone) up",   category: "verbs", example: "Gisingin mo ako bukas — Wake me up tomorrow." },
  { fil: "Magpadala",   eng: "To send",                category: "verbs" },
  { fil: "Tumanggap",   eng: "To receive / accept",    category: "verbs" },
  { fil: "Pumili",      eng: "To choose / pick",       category: "verbs" },
  { fil: "Magdesisyon", eng: "To decide",              category: "verbs" },
  { fil: "Maniwala",    eng: "To believe",             category: "verbs", example: "Hindi ako naniniwala — I don't believe it." },
  { fil: "Matakot",     eng: "To be scared / fear",    category: "verbs" },
  { fil: "Magtiyaga",   eng: "To persevere / be patient", category: "verbs" },
  { fil: "Makiusap",    eng: "To plead / request humbly", category: "verbs" },
  { fil: "Magsinungaling", eng: "To lie / tell a lie", category: "verbs" },

  // ── PARTICLES ────────────────────────────────────────────
  // Enclitic particles are the heartbeat of natural Filipino speech
  { fil: "na",    eng: "Already / Now / (change of state)", category: "particles",
    example: "Kumain na ako — I've already eaten. | Tara na — Let's go now." },
  { fil: "pa",    eng: "Still / Yet / More / Another",      category: "particles",
    example: "Wala pa — Not yet. | Isa pa — One more. | Natutulog pa siya — He's still sleeping." },
  { fil: "lang / lamang", eng: "Only / Just / Merely",      category: "particles",
    example: "Sandali lang — Just a moment. | Isa lang — Just one. (Softens requests too.)" },
  { fil: "ba",    eng: "Question marker (yes/no)",          category: "particles",
    example: "Kumain ka na ba? — Have you eaten yet? | Totoo ba? — Is that true?" },
  { fil: "nga",   eng: "Affirmation / Emphasis / Indeed",   category: "particles",
    example: "Oo nga — Yes, indeed. | Ano nga ulit? — What was it again? | Tama nga — That's right." },
  { fil: "naman", eng: "On the other hand / Softener / Also (contrast)", category: "particles",
    example: "Ikaw naman — You, on the other hand. | Sige naman — Come on, please. | Ano naman iyon? — What's that supposed to mean?" },
  { fil: "kasi",  eng: "Because / The reason is",          category: "particles",
    example: "Kasi gutom ako — Because I'm hungry. | Bakit? Kasi. — Why? Just because." },
  { fil: "daw / raw", eng: "Reportedly / They say / Supposedly", category: "particles",
    example: "Masarap daw — They say it's delicious. | Darating daw siya — Apparently he's coming. (Use 'raw' after vowels.)" },
  { fil: "pala",  eng: "Oh, I see / I didn't realize / So that's why", category: "particles",
    example: "Ikaw pala! — Oh, it was you! | Ganoon pala — Oh, so that's how it is." },
  { fil: "yata",  eng: "I think / Probably / Seems like",   category: "particles",
    example: "Wala yata siya — I don't think he's there. | Malayo yata — It seems far." },
  { fil: "eh",    eng: "(Mild filler) Well / But / You see", category: "particles",
    example: "Eh, ganoon talaga — Well, that's just how it is. (Common sentence-ender; hard to translate directly.)" },
  { fil: "din / rin", eng: "Also / Too / As well",          category: "particles",
    example: "Ako rin — Me too. | Gutom din ako — I'm also hungry. (Use 'rin' after vowels.)" },
  { fil: "talaga", eng: "Really / Truly / Indeed",          category: "particles",
    example: "Talaga? — Really? | Masarap talaga — It's really delicious. | Hindi ko talaga alam — I really don't know." },
  { fil: "muna",  eng: "First / For now / Before anything else", category: "particles",
    example: "Kumain muna tayo — Let's eat first. | Sandali muna — Hold on a moment. | Hintay muna — Wait first." },
  { fil: "na lang", eng: "Just / Might as well / Let's just", category: "particles",
    example: "Sige na lang — Let's just go ahead. | Wag na lang — Let's just not. | Ako na lang — I'll just do it." },
  { fil: "po / ho", eng: "Respect particle (speech to elders/strangers)", category: "particles",
    example: "Salamat po — Thank you (respectful). | Oo po — Yes (respectful). 'Ho' is softer; both show deference." },

  // ── ADJECTIVES ───────────────────────────────────────────
  { fil: "Maganda",    eng: "Beautiful / Pretty / Nice", category: "adjectives",
    example: "Magandang tanawin — A beautiful view." },
  { fil: "Pangit",     eng: "Ugly / Unpleasant",        category: "adjectives" },
  { fil: "Malaki",     eng: "Big / Large",               category: "adjectives",
    example: "Malaking bahay — A big house." },
  { fil: "Maliit",     eng: "Small / Little",            category: "adjectives" },
  { fil: "Mahal",      eng: "Expensive / Beloved / Dear", category: "adjectives",
    example: "Mahal na mahal kita — I love you very much. | Mahal ang presyo — The price is expensive." },
  { fil: "Mura",       eng: "Cheap / Inexpensive",       category: "adjectives" },
  { fil: "Mainit",     eng: "Hot / Warm",                category: "adjectives",
    example: "Mainit ang panahon — The weather is hot." },
  { fil: "Malamig",    eng: "Cold / Cool",               category: "adjectives" },
  { fil: "Masarap",    eng: "Delicious / Tasty / Enjoyable", category: "adjectives",
    example: "Masarap ang pagkain — The food is delicious." },
  { fil: "Matamis",    eng: "Sweet",                     category: "adjectives" },
  { fil: "Maasim",     eng: "Sour",                      category: "adjectives" },
  { fil: "Mapait",     eng: "Bitter",                    category: "adjectives" },
  { fil: "Maalat",     eng: "Salty",                     category: "adjectives" },
  { fil: "Mabilis",    eng: "Fast / Quick",              category: "adjectives" },
  { fil: "Mabagal",    eng: "Slow",                      category: "adjectives" },
  { fil: "Malakas",    eng: "Strong / Loud",             category: "adjectives",
    example: "Malakas na ulan — Heavy rain. | Malakas ang tunog — The sound is loud." },
  { fil: "Mahina",     eng: "Weak / Soft / Quiet",       category: "adjectives" },
  { fil: "Mabuti",     eng: "Good / Well / Kind",        category: "adjectives",
    example: "Mabuting tao — A good person. | Mabuti naman — That's good." },
  { fil: "Masama",     eng: "Bad / Evil / Unpleasant",   category: "adjectives" },
  { fil: "Matanda",    eng: "Old / Elderly",             category: "adjectives" },
  { fil: "Bago",       eng: "New / Recent",              category: "adjectives" },
  { fil: "Luma",       eng: "Old (of things) / Worn",    category: "adjectives" },
  { fil: "Mataas",     eng: "Tall / High",               category: "adjectives" },
  { fil: "Mababa",     eng: "Short / Low",               category: "adjectives" },
  { fil: "Payat",      eng: "Thin / Slim",               category: "adjectives" },
  { fil: "Mataba",     eng: "Fat / Chubby / Plump",      category: "adjectives" },
  { fil: "Maliwanag",  eng: "Bright / Clear / Well-lit", category: "adjectives" },
  { fil: "Madilim",    eng: "Dark / Dim",                category: "adjectives" },
  { fil: "Maingay",    eng: "Noisy / Loud",              category: "adjectives" },
  { fil: "Tahimik",    eng: "Quiet / Peaceful / Calm",   category: "adjectives" },
  { fil: "Marami",     eng: "Many / A lot / Much",       category: "adjectives",
    example: "Maraming salamat — Many thanks. | Maraming tao — A lot of people." },
  { fil: "Kaunti / Konti", eng: "Few / A little / Not much", category: "adjectives" },
  { fil: "Libre",      eng: "Free (no cost)",            category: "adjectives" },

  // ── GRAMMAR CONCEPTS ─────────────────────────────────────
  { fil: "Ang",  eng: "Topic/subject marker (specific noun)", category: "grammar",
    example: "Ang bata ay kumain — The child ate. Ang marks the topic — what the sentence is 'about'." },
  { fil: "Ng",   eng: "Object marker / 'of' (non-topic noun)", category: "grammar",
    example: "Bumili ako ng tinapay — I bought bread. 'ng' marks the non-focused object." },
  { fil: "Sa",   eng: "Location / direction / indirect object marker", category: "grammar",
    example: "Pumunta siya sa tindahan — He went to the store. Sa = to/in/at/for depending on context." },
  { fil: "Ay",   eng: "Formal topic linker (inverted sentence order)", category: "grammar",
    example: "Ang bata ay maganda — The child is beautiful. 'Ay' flips verb-first order to topic-first." },
  { fil: "Na / -ng  (ligature)", eng: "Linker connecting modifier to noun", category: "grammar",
    example: "'na' after consonants: magandang babae (beautiful woman). '-ng' after vowels: mabuting tao (good person)." },
  { fil: "Mayroon / Meron", eng: "There is / To have (existential)", category: "grammar",
    example: "Mayroon akong pera — I have money. Meron na ba? — Is there some already?" },
  { fil: "Wala",  eng: "There is none / Does not have / Nothing", category: "grammar",
    example: "Wala akong pera — I have no money. Wala na siya — He's no longer here / He's gone." },
  { fil: "Hindi pa", eng: "Not yet",                              category: "grammar",
    example: "Hindi pa ako kumakain — I haven't eaten yet. Contrast with 'hindi na' = no longer." },
  { fil: "Hindi na", eng: "No longer / Not anymore",             category: "grammar",
    example: "Hindi na siya narito — He's no longer here." },
  { fil: "Tayo vs Kami", eng: "We (inclusive) vs We (exclusive)", category: "grammar",
    example: "Tayo = includes the listener. Kami = excludes the listener. 'Kumain tayo' = Let's eat (you too)." },
  { fil: "Ako / Ko / Akin", eng: "I (topic) / My·I (object) / Mine (location)", category: "grammar",
    example: "Ako ay... | Binili ko... (I bought) | Para sa akin... (for me). Three forms for first person!" },
  { fil: "Ikaw·Ka / Mo / Iyo", eng: "You (topic) / Your·You / Yours", category: "grammar",
    example: "Ikaw = full topic form. Ka = short post-verb form. Gusto mo? — Do you want? | Iyo ito — This is yours." },
  { fil: "Siya / Niya / Kanya", eng: "He·She (topic) / His·Her (object) / His·Hers (location)", category: "grammar",
    example: "Filipino has no gender in pronouns — siya = he or she." },
  { fil: "-um- infix (actor focus, completed)", eng: "Completed actor-focus action", category: "grammar",
    example: "kain → kumain (ate) | lakad → lumakad (walked) | bili → bumili (bought). The actor is the topic." },
  { fil: "Nag- prefix (completed, mag- verb class)", eng: "Completed action for mag- verb class", category: "grammar",
    example: "magluto → nagluto (cooked) | maglaro → naglaro (played) | magtrabaho → nagtrabaho (worked)." },
  { fil: "Ongoing aspect: -um- → -uM-uM- / mag- → nagCa-", eng: "Ongoing/continuous action (reduplication)", category: "grammar",
    example: "kumain → kumakain (is eating) | magluto → nagluluto (is cooking). Reduplicate first syllable of root." },
  { fil: "Contemplated aspect: mag- prefix", eng: "Future / planned action (contemplated aspect)", category: "grammar",
    example: "magluto (will cook) | maglaro (will play) | kumain → kakain (will eat). Action not yet started." },
  { fil: "-in suffix (object focus, completed)", eng: "Object-focus verb: the object is the topic", category: "grammar",
    example: "Binili ko ang tinapay — I bought the bread ('the bread' is topic). Compare: Bumili ako ng tinapay (actor focus)." },
  { fil: "Kung",  eng: "If / Whether",                          category: "grammar",
    example: "Kung gusto mo — If you want. | Hindi ko alam kung totoo — I don't know whether it's true." },
  { fil: "Kapag / Pag", eng: "When / Whenever (future or habitual)", category: "grammar",
    example: "Kapag gutom ka — When you're hungry. | Pag-dating niya — When he arrives." },
  { fil: "Noong", eng: "When (past) / Back when",               category: "grammar",
    example: "Noong bata pa ako — When I was still young. | Noong isang araw — One day (in the past)." },
  { fil: "Dahil sa / Kasi", eng: "Because of / Due to",         category: "grammar",
    example: "Dahil sa ulan, hindi kami lumabas — Because of the rain, we didn't go out." },
  { fil: "Para sa / Para kay", eng: "For (purpose or person)",  category: "grammar",
    example: "Para sa inyo — For you all (para sa + non-personal). Para kay Maria — For Maria (para kay + personal)." },
  { fil: "Kahit",  eng: "Even if / Even though / Any-",         category: "grammar",
    example: "Kahit umuulan, lalabas ako — Even if it rains, I'll go out. | Kahit sino — Anyone." },

  // ── SLANG & COLLOQUIAL ───────────────────────────────────
  { fil: "Grabe!",      eng: "Wow! / So intense! / That's a lot!", category: "slang",
    example: "Grabe ka talaga! — You're really something! | Grabe naman — That's too much." },
  { fil: "Kilig",       eng: "Romantic giddiness / Butterflies",   category: "slang",
    example: "Kilig na kilig ako — I have such butterflies. (No direct English equivalent.)" },
  { fil: "Diskarte",    eng: "Street smarts / Resourcefulness / A way around things", category: "slang",
    example: "Maghanap ka ng diskarte — Find a way. Filipinos are proud of their diskarte." },
  { fil: "Gigil",       eng: "Urge to pinch something overwhelmingly cute", category: "slang",
    example: "Gigil na gigil ako sa kanya — I have an irresistible urge to pinch them. (Untranslatable!)" },
  { fil: "Tampo",       eng: "Sulking to show you're hurt (wanting to be coaxed)", category: "slang",
    example: "Nagtatampo siya sa akin — She's sulking at me. Different from anger; it's an appeal for attention." },
  { fil: "Hay nako!",   eng: "Oh my! / Good grief! / Ugh!",        category: "slang",
    example: "Hay nako, ano ba yan! — Oh my, what is that!" },
  { fil: "Naku!",       eng: "Oh no! / Oh my! (mild alarm)",       category: "slang",
    example: "Naku, nakalimutan ko — Oh no, I forgot." },
  { fil: "Ano ba!",     eng: "Come on! / What the heck! / Seriously?", category: "slang",
    example: "Ano ba yan! — What the heck is that! (mild frustration)" },
  { fil: "OA",          eng: "Over-acting / Being extra / Exaggerating", category: "slang",
    example: "OA ka naman — You're being so extra. From 'over-acting'." },
  { fil: "Sana all",    eng: "I wish everyone had that / Lucky you", category: "slang",
    example: "Libre ang pasok? Sana all — Free entry? I wish that was for everyone." },
  { fil: "Charot / Char", eng: "Just kidding / Just joking",       category: "slang",
    example: "Maganda ka. Charot! — You're beautiful. Just kidding!" },
  { fil: "Pre / Pare",  eng: "Dude / Bro / Mate",                  category: "slang",
    example: "Tara na, pre! — Let's go, dude! From 'compadre'." },
  { fil: "Petmalu",     eng: "Amazing / Awesome (slang)",          category: "slang",
    example: "Petmalu ka talaga! — You're really awesome! Reversed syllables of 'malupet' (extreme)." },
  { fil: "Lodi",        eng: "Idol / Someone you admire (slang)",  category: "slang",
    example: "Ikaw ang lodi ko — You're my idol. Reversed syllables of 'idolo'." },
  { fil: "Beshie / Bes", eng: "Best friend / Bestie",             category: "slang",
    example: "Beshie ko siya — She's my bestie. From 'best friend'." },
  { fil: "Ewan ko / Aywan", eng: "I don't know (casual)",         category: "slang",
    example: "Ewan ko sa kanya — I don't know about him. More casual than 'Hindi ko alam'." },
  { fil: "Basta",       eng: "Just / As long as / Never mind / Period", category: "slang",
    example: "Basta ikaw — As long as it's you. | Basta, wag ka na lang — Just don't, period. Versatile filler." },
  { fil: "Luto",        eng: "Rigged / Fixed / Corrupt (slang)",  category: "slang",
    example: "Luto ang resulta — The results were rigged. Literally 'cooked'; metaphor for manipulation." },
  { fil: "Chika",       eng: "Gossip / Latest news / To chat",    category: "slang",
    example: "Ano ang chika? — What's the latest gossip? | Chikahan tayo — Let's have a chat." },
  { fil: "Tsismis",     eng: "Gossip / Rumor",                    category: "slang",
    example: "Mahilig siya sa tsismis — She loves gossip. One of the most common Filipino pastimes." },
  { fil: "Gigil, kilig, tampo, lihi", eng: "Untranslatable Filipino emotions (see each individually)", category: "slang",
    example: "Filipino has many emotion words with no English equivalent, showing the richness of the culture." },

  // More advanced phrases (expand existing phrases category)
  { fil: "Pwede ba akong…?",        eng: "May I…? / Could I…?",         category: "phrases",
    example: "Pwede ba akong umupo dito? — May I sit here?" },
  { fil: "Gusto mo bang…?",         eng: "Do you want to…?",             category: "phrases",
    example: "Gusto mo bang kumain? — Do you want to eat?" },
  { fil: "Paano ba…?",              eng: "How exactly…? / How do you…?", category: "phrases",
    example: "Paano ba pumunta sa Maynila? — How exactly do you get to Manila?" },
  { fil: "Sa tingin ko…",           eng: "I think… / In my opinion…",    category: "phrases",
    example: "Sa tingin ko, tama ka — I think you're right." },
  { fil: "Kung maaari lang",        eng: "If possible / If it's okay",   category: "phrases" },
  { fil: "Depende",                 eng: "It depends",                   category: "phrases" },
  { fil: "Sa madaling salita",      eng: "In short / To put it simply",  category: "phrases" },
  { fil: "Sa katunayan",            eng: "In fact / Actually / The truth is", category: "phrases" },
  { fil: "Lalo na",                 eng: "Especially / Most of all",     category: "phrases" },
  { fil: "Bukod doon / Bukod pa rito", eng: "Besides that / On top of that", category: "phrases" },
  { fil: "Kahit papaano",           eng: "At least / Somehow / Either way", category: "phrases" },
  { fil: "Di bale na",              eng: "Never mind / Don't worry about it", category: "phrases" },
  { fil: "Naiintindihan mo ba?",    eng: "Do you understand?",           category: "phrases" },
  { fil: "Ganoon ba?",              eng: "Is that so? / Really? / Oh?",  category: "phrases" },
  { fil: "Bahala na",               eng: "Leave it to fate / Whatever happens", category: "phrases",
    example: "'Bahala na' embodies a Filipino cultural attitude of accepting uncertainty with equanimity." },
];

// Category metadata
const CATEGORIES = {
  all:        { label: "All",           emoji: "🌟" },
  greetings:  { label: "Greetings",     emoji: "👋" },
  phrases:    { label: "Phrases",       emoji: "💬" },
  numbers:    { label: "Numbers",       emoji: "🔢" },
  family:     { label: "Family",        emoji: "👨‍👩‍👧" },
  food:       { label: "Food & Drink",  emoji: "🍚" },
  travel:     { label: "Travel",        emoji: "✈️" },
  colors:     { label: "Colors",        emoji: "🎨" },
  time:       { label: "Time & Days",   emoji: "📅" },
  verbs:      { label: "Verbs",         emoji: "🏃" },
  adjectives: { label: "Adjectives",    emoji: "✨" },
  particles:  { label: "Particles",     emoji: "⚡" },
  grammar:    { label: "Grammar",       emoji: "🧠" },
  slang:      { label: "Slang",         emoji: "😎" },
};
