// ============================================================
//  Mabuhay! — Filipino Vocabulary Database
//  Each entry: { fil, eng, category, romanization?, example? }
// ============================================================

const VOCAB = [
  // ── GREETINGS & PLEASANTRIES ────────────────────────────
  { fil: "Kumusta?",           eng: "How are you? / Hello",       category: "greetings", example: "Kumusta ka? — How are you?" },
  { fil: "Mabuhay!",           eng: "Welcome! / Long live! / Cheers!", category: "greetings", example: "Mabuhay sa Pilipinas! — Welcome to the Philippines!" },
  { fil: "Magandang umaga",    eng: "Good morning",               category: "greetings", example: "Magandang umaga po! — Good morning (polite)." },
  { fil: "Magandang hapon",    eng: "Good afternoon",             category: "greetings" },
  { fil: "Magandang gabi",     eng: "Good evening",               category: "greetings" },
  { fil: "Paalam",             eng: "Goodbye / Farewell",         category: "greetings", example: "Paalam na! — Goodbye now!" },
  { fil: "Salamat",            eng: "Thank you",                  category: "greetings", example: "Maraming salamat — Thank you very much." },
  { fil: "Walang anuman",      eng: "You're welcome",             category: "greetings" },
  { fil: "Oo",                 eng: "Yes",                        category: "greetings" },
  { fil: "Hindi",              eng: "No",                         category: "greetings" },
  { fil: "Paumanhin",          eng: "Excuse me / I'm sorry",      category: "greetings", example: "Paumanhin, nasaan ang banyo? — Excuse me, where is the restroom?" },
  { fil: "Po / Opo",           eng: "Polite particle / Yes (polite)", category: "greetings", example: "Used to show respect to elders." },
  { fil: "Sige",               eng: "Okay / Go ahead / Sure",     category: "greetings", example: "Sige, tara na! — Okay, let's go!" },
  { fil: "Naman",              eng: "Also / Indeed (emphasis)",   category: "greetings", example: "Oo naman — Of course." },
  { fil: "Tara / Halika",      eng: "Come on / Let's go",         category: "greetings", example: "Tara, kumain tayo! — Come on, let's eat!" },

  // ── COMMON PHRASES ──────────────────────────────────────
  { fil: "Ano ang pangalan mo?",     eng: "What is your name?",          category: "phrases" },
  { fil: "Ang pangalan ko ay…",      eng: "My name is…",                 category: "phrases" },
  { fil: "Saan ka galing?",          eng: "Where are you from?",         category: "phrases" },
  { fil: "Hindi ko maintindihan",    eng: "I don't understand",          category: "phrases" },
  { fil: "Pakiulit",                 eng: "Please repeat that",          category: "phrases" },
  { fil: "Nagsasalita ka ba ng Ingles?", eng: "Do you speak English?",   category: "phrases" },
  { fil: "Magkano?",                 eng: "How much?",                   category: "phrases", example: "Magkano ang isda? — How much is the fish?" },
  { fil: "Nasaan ang…?",            eng: "Where is…?",                  category: "phrases" },
  { fil: "Gusto ko…",               eng: "I want / I like…",            category: "phrases", example: "Gusto ko ng kape — I want coffee." },
  { fil: "Kailangan ko…",           eng: "I need…",                     category: "phrases" },
  { fil: "Gutom na ako",             eng: "I'm hungry",                  category: "phrases" },
  { fil: "Uhaw na ako",              eng: "I'm thirsty",                 category: "phrases" },
  { fil: "Pagod na ako",             eng: "I'm tired",                   category: "phrases" },
  { fil: "Masaya ako",               eng: "I am happy",                  category: "phrases" },
  { fil: "Mahal kita",               eng: "I love you",                  category: "phrases" },
  { fil: "Miss na kita",             eng: "I miss you",                  category: "phrases" },
  { fil: "Tulong!",                  eng: "Help!",                       category: "phrases" },
  { fil: "Huwag!",                   eng: "Don't! / Stop!",              category: "phrases" },
  { fil: "Sandali lang",             eng: "Just a moment / Wait",        category: "phrases" },
  { fil: "Bakit?",                   eng: "Why?",                        category: "phrases" },
  { fil: "Kailan?",                  eng: "When?",                       category: "phrases" },
  { fil: "Sino?",                    eng: "Who?",                        category: "phrases" },
  { fil: "Ano?",                     eng: "What?",                       category: "phrases" },
  { fil: "Gaano?",                   eng: "How much / How many?",        category: "phrases" },
  { fil: "Alam mo ba?",              eng: "Do you know?",                category: "phrases" },

  // ── NUMBERS ─────────────────────────────────────────────
  { fil: "Isa",       eng: "One (1)",    category: "numbers" },
  { fil: "Dalawa",    eng: "Two (2)",    category: "numbers" },
  { fil: "Tatlo",     eng: "Three (3)", category: "numbers" },
  { fil: "Apat",      eng: "Four (4)",  category: "numbers" },
  { fil: "Lima",      eng: "Five (5)",  category: "numbers" },
  { fil: "Anim",      eng: "Six (6)",   category: "numbers" },
  { fil: "Pito",      eng: "Seven (7)", category: "numbers" },
  { fil: "Walo",      eng: "Eight (8)", category: "numbers" },
  { fil: "Siyam",     eng: "Nine (9)",  category: "numbers" },
  { fil: "Sampu",     eng: "Ten (10)",  category: "numbers" },
  { fil: "Labing-isa",eng: "Eleven (11)", category: "numbers" },
  { fil: "Labindalawa",eng: "Twelve (12)", category: "numbers" },
  { fil: "Dalawampu", eng: "Twenty (20)", category: "numbers" },
  { fil: "Tatlumpu",  eng: "Thirty (30)", category: "numbers" },
  { fil: "Isang daan",eng: "One hundred (100)", category: "numbers" },
  { fil: "Isang libo", eng: "One thousand (1,000)", category: "numbers" },

  // ── FAMILY ──────────────────────────────────────────────
  { fil: "Pamilya",    eng: "Family",            category: "family" },
  { fil: "Nanay / Inay", eng: "Mother / Mom",    category: "family" },
  { fil: "Tatay / Itay", eng: "Father / Dad",    category: "family" },
  { fil: "Kapatid",    eng: "Sibling",            category: "family" },
  { fil: "Kuya",       eng: "Older brother",      category: "family", example: "Also used as a respectful address for older men." },
  { fil: "Ate",        eng: "Older sister",        category: "family", example: "Also used as a respectful address for older women." },
  { fil: "Anak",       eng: "Child / Son / Daughter", category: "family" },
  { fil: "Lolo",       eng: "Grandfather",        category: "family" },
  { fil: "Lola",       eng: "Grandmother",        category: "family" },
  { fil: "Tito",       eng: "Uncle",              category: "family" },
  { fil: "Tita",       eng: "Aunt",               category: "family" },
  { fil: "Pinsan",     eng: "Cousin",             category: "family" },
  { fil: "Asawa",      eng: "Spouse",             category: "family" },
  { fil: "Lalaki",     eng: "Man / Male",         category: "family" },
  { fil: "Babae",      eng: "Woman / Female",     category: "family" },
  { fil: "Bata",       eng: "Child / Young",      category: "family" },

  // ── FOOD & DRINK ────────────────────────────────────────
  { fil: "Kanin",    eng: "Cooked rice",           category: "food" },
  { fil: "Ulam",     eng: "Viand / Side dish",     category: "food", example: "The dish eaten with rice." },
  { fil: "Asin",     eng: "Salt",                  category: "food" },
  { fil: "Asukal",   eng: "Sugar",                 category: "food" },
  { fil: "Tubig",    eng: "Water",                 category: "food" },
  { fil: "Gatas",    eng: "Milk",                  category: "food" },
  { fil: "Kape",     eng: "Coffee",                category: "food" },
  { fil: "Tinapay",  eng: "Bread",                 category: "food" },
  { fil: "Karne",    eng: "Meat",                  category: "food" },
  { fil: "Isda",     eng: "Fish",                  category: "food" },
  { fil: "Manok",    eng: "Chicken",               category: "food" },
  { fil: "Baboy",    eng: "Pig / Pork",            category: "food" },
  { fil: "Gulay",    eng: "Vegetables",            category: "food" },
  { fil: "Prutas",   eng: "Fruit",                 category: "food" },
  { fil: "Itlog",    eng: "Egg",                   category: "food" },
  { fil: "Adobo",    eng: "Adobo (vinegar & soy dish)", category: "food", example: "The most iconic Filipino dish." },
  { fil: "Sinigang", eng: "Sinigang (sour tamarind soup)", category: "food" },
  { fil: "Sorbetes", eng: "Ice cream",             category: "food" },
  { fil: "Merienda", eng: "Afternoon snack",       category: "food", example: "A beloved Filipino tradition of a light mid-afternoon meal." },

  // ── TRAVEL ──────────────────────────────────────────────
  { fil: "Eroplano",   eng: "Airplane",            category: "travel" },
  { fil: "Barko",      eng: "Ship / Boat",         category: "travel" },
  { fil: "Jeepney",    eng: "Jeepney (local bus)", category: "travel", example: "The iconic, colorfully decorated Filipino public transport." },
  { fil: "Trike",      eng: "Tricycle (motorbike sidecar)", category: "travel" },
  { fil: "Paliparan",  eng: "Airport",             category: "travel" },
  { fil: "Daan",       eng: "Road / Street",       category: "travel" },
  { fil: "Tulay",      eng: "Bridge",              category: "travel" },
  { fil: "Ospital",    eng: "Hospital",            category: "travel" },
  { fil: "Simbahan",   eng: "Church",              category: "travel" },
  { fil: "Palengke",   eng: "Market",              category: "travel" },
  { fil: "Bangko",     eng: "Bank",                category: "travel" },
  { fil: "Paaralan",   eng: "School",              category: "travel" },
  { fil: "Bahay",      eng: "House / Home",        category: "travel" },
  { fil: "Banyo",      eng: "Bathroom / Restroom", category: "travel" },
  { fil: "Kanan",      eng: "Right (direction)",   category: "travel" },
  { fil: "Kaliwa",     eng: "Left (direction)",    category: "travel" },
  { fil: "Diretso",    eng: "Straight ahead",      category: "travel" },
  { fil: "Malapit",    eng: "Near / Close",        category: "travel" },
  { fil: "Malayo",     eng: "Far",                 category: "travel" },

  // ── COLORS ──────────────────────────────────────────────
  { fil: "Pula",         eng: "Red",     category: "colors" },
  { fil: "Berde",        eng: "Green",   category: "colors" },
  { fil: "Asul",         eng: "Blue",    category: "colors" },
  { fil: "Dilaw",        eng: "Yellow",  category: "colors" },
  { fil: "Puti",         eng: "White",   category: "colors" },
  { fil: "Itim",         eng: "Black",   category: "colors" },
  { fil: "Kulay-abo",    eng: "Gray",    category: "colors" },
  { fil: "Kahel",        eng: "Orange",  category: "colors" },
  { fil: "Rosas",        eng: "Pink",    category: "colors" },
  { fil: "Kayumanggi",   eng: "Brown",   category: "colors" },
  { fil: "Lila / Ube",   eng: "Purple",  category: "colors" },

  // ── TIME & DAYS ──────────────────────────────────────────
  { fil: "Ngayon",       eng: "Now / Today",        category: "time" },
  { fil: "Bukas",        eng: "Tomorrow",            category: "time" },
  { fil: "Kahapon",      eng: "Yesterday",           category: "time" },
  { fil: "Umaga",        eng: "Morning",             category: "time" },
  { fil: "Tanghali",     eng: "Noon / Midday",       category: "time" },
  { fil: "Hapon",        eng: "Afternoon",           category: "time" },
  { fil: "Gabi",         eng: "Evening / Night",     category: "time" },
  { fil: "Lunes",        eng: "Monday",              category: "time" },
  { fil: "Martes",       eng: "Tuesday",             category: "time" },
  { fil: "Miyerkules",   eng: "Wednesday",           category: "time" },
  { fil: "Huwebes",      eng: "Thursday",            category: "time" },
  { fil: "Biyernes",     eng: "Friday",              category: "time" },
  { fil: "Sabado",       eng: "Saturday",            category: "time" },
  { fil: "Linggo",       eng: "Sunday / Week",       category: "time", example: "Linggo also means 'week'." },
  { fil: "Taon",         eng: "Year",                category: "time" },
  { fil: "Buwan",        eng: "Month / Moon",        category: "time" },
  { fil: "Oras",         eng: "Hour / Time",         category: "time" },

  // ── COMMON VERBS ─────────────────────────────────────────
  { fil: "Kumain",    eng: "To eat",         category: "verbs", example: "Kumain tayo! — Let's eat!" },
  { fil: "Uminom",    eng: "To drink",       category: "verbs" },
  { fil: "Matulog",   eng: "To sleep",       category: "verbs" },
  { fil: "Gumising",  eng: "To wake up",     category: "verbs" },
  { fil: "Maglakad",  eng: "To walk",        category: "verbs" },
  { fil: "Tumakbo",   eng: "To run",         category: "verbs" },
  { fil: "Magtrabaho",eng: "To work",        category: "verbs" },
  { fil: "Mag-aral",  eng: "To study",       category: "verbs" },
  { fil: "Maglaro",   eng: "To play",        category: "verbs" },
  { fil: "Manood",    eng: "To watch",       category: "verbs" },
  { fil: "Makinig",   eng: "To listen",      category: "verbs" },
  { fil: "Magsalita", eng: "To speak / talk",category: "verbs" },
  { fil: "Bumasa",    eng: "To read",        category: "verbs" },
  { fil: "Sumulat",   eng: "To write",       category: "verbs" },
  { fil: "Bumili",    eng: "To buy",         category: "verbs" },
  { fil: "Magbayad",  eng: "To pay",         category: "verbs" },
  { fil: "Pumunta",   eng: "To go (to a place)", category: "verbs" },
  { fil: "Bumalik",   eng: "To return / come back", category: "verbs" },
  { fil: "Umalis",    eng: "To leave",       category: "verbs" },
  { fil: "Lumapit",   eng: "To come near / approach", category: "verbs" },
  { fil: "Magbigay",  eng: "To give",        category: "verbs" },
  { fil: "Kumuha",    eng: "To take / get",  category: "verbs" },
  { fil: "Magtanong", eng: "To ask",         category: "verbs" },
  { fil: "Sumagot",   eng: "To answer",      category: "verbs" },
  { fil: "Tumulong",  eng: "To help",        category: "verbs" },
];

// Category metadata
const CATEGORIES = {
  all:       { label: "All",          emoji: "🌟" },
  greetings: { label: "Greetings",    emoji: "👋" },
  phrases:   { label: "Phrases",      emoji: "💬" },
  numbers:   { label: "Numbers",      emoji: "🔢" },
  family:    { label: "Family",       emoji: "👨‍👩‍👧" },
  food:      { label: "Food & Drink", emoji: "🍚" },
  travel:    { label: "Travel",       emoji: "✈️" },
  colors:    { label: "Colors",       emoji: "🎨" },
  time:      { label: "Time & Days",  emoji: "📅" },
  verbs:     { label: "Verbs",        emoji: "🏃" },
};
